[package]
name = "estree-detect-requires"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]

[dependencies]
easter = { version = "0.0.5", path = "../../../esprit/crates/easter" }
esprit = { version = "0.0.5", path = "../../../esprit" }

[lib]
doctest = false
